### ISSUE TITLE
Envoy - failed to load dynamic library opentracing versions are incomptable

### ISSUE THREAD

**Issue by dmichel1** [jaegertracing/jaeger-client-cpp#277]
I tried using this library with v1.18.3 of Envoy and it causes the below error when using the `dynamic_ot` tracer.

```
opentracing: failed to load dynamic library: opentracing: versions of opentracing libraries are incompatible
```

```yaml
# envoy config
          tracing:
            provider:
              name: envoy.tracers.dynamic_ot
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.DynamicOtConfig
                 ...
```

I'm not sure if when https://github.com/jaegertracing/jaeger-client-cpp/pull/209 bumped the opentracing library to 1.6.0 if this broke compatibility with Envoy, as its still on version [1.5.1][1].

[1]: https://github.com/envoyproxy/envoy/blob/b65b397652e5a627a9f3b0adcfe840d80dd57c03/bazel/repository_locations.bzl#L294
